name: promote-prod-from-preprod-branch

on:
  push:
    branches:
      - master
      - beta
      - alpha

env:
  NPM_TOKEN: ${{ secrets.BOT_REGISTRY_TOKEN }}
  NPM_CONFIG_USERCONFIG: .npmrc

jobs:
  publish:
    if: |
      !contains(github.event.head_commit.author.name, 'james-pontte')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-node-modules
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Generate build
        run: npm run build

      - name: Promote under production version
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
        run: |
          # Remove comment to generate release.
          # npx semantic-release
